HOPSFS-191 Bump Hops Hadoop Version to 3.2.0.15-SNAPSHOT
logicalclocks/incubator-uniffle pull request #4
Opened 2024-10-07 12:48 UTC by smkniazi

HOPSFS-191 Bump Hops Hadoop Version to 3.2.0.15-SNAPSHOT

2024-10-10 12:48 UTC, maismail requested changes
I suppose we should bump version of the docker image as well but not sure what should be the version format since i think 0.9.0 is the version of rss so probably we need to amend another version `0.9.0.1` or something @gibchikafa probably would be better to answer this
https://github.com/logicalclocks/incubator-uniffle/blob/branch-0.9/version.txt

2024-10-15 08:40 UTC, gibchikafa commented
Let's change the version to `0.9.0.1`. We then need to change version in the helm chart.

2024-10-15 08:43 UTC, gibchikafa commented
https://github.com/logicalclocks/hopsworks-helm/blob/ff0534ac9c1712513d453be85ad19ee388184b3f/charts/spark/values.yaml#L56

2024-10-15 13:22 UTC, gibchikafa approved these changes

2024-10-16 07:50 UTC, maismail approved these changes

2024-10-16 08:22 UTC, merged